train_dataset: ???
validation_datasets: ???
log_dir: ???


sample_rate: 44100
n_mel_channels: 80
n_window_size: 2048
n_window_stride: 512
n_fft: 2048
lowfreq: 0
highfreq: null
window: hann

batch_size: 16

train_n_segments: 16384
train_max_duration: 30
train_min_duration: 1

val_n_segments: 131072
val_max_duration: 30
val_min_duration: 3

model:
  max_epochs: ${trainer.max_epochs}
  l1_loss_factor: 45
  denoise_strength: 0.0025
  preprocessor:
    _target_: nemo.collections.asr.parts.preprocessing.features.FilterbankFeatures
    nfilt: ${n_mel_channels}
    lowfreq: ${lowfreq}
    highfreq: ${highfreq}
    n_fft: ${n_fft}
    n_window_size: ${n_window_size}
    n_window_stride: ${n_window_stride}
    pad_to: 0
    pad_value: -11.52
    sample_rate: ${sample_rate}
    window: ${window}
    normalize: null
    preemph: null
    dither: 0.0
    frame_splicing: 1
    log: true
    log_zero_guard_type: clamp
    log_zero_guard_value: 1e-05
    mag_power: 1.0
    use_grads: false
    exact_pad: true
  
  generator:
    _target_: nemo.collections.tts.modules.hifigan_modules.Generator
    resblock: 1
    upsample_rates: [8,8,4,2]
    upsample_kernel_sizes: [16,16,4,4]
    upsample_initial_channel: 512
    resblock_kernel_sizes: [3,7,11]
    resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]

  train_ds:
    dataset:
      _target_: "nemo.collections.tts.data.dataset.VocoderDataset"
      manifest_filepath: ${train_dataset}
      sample_rate: ${sample_rate}
      n_segments: ${train_n_segments}
      max_duration: ${train_max_duration}
      min_duration: ${train_min_duration}
      load_precomputed_mel: true
      hop_length: ${n_window_stride}
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: ${batch_size}
      num_workers: 12
      pin_memory: true
  validation_ds:
    dataset:
      _target_: "nemo.collections.tts.data.dataset.VocoderDataset"
      manifest_filepath: ${validation_datasets}
      sample_rate: ${sample_rate}
      n_segments: ${val_n_segments}
      max_duration: ${val_max_duration}
      min_duration: ${val_min_duration}
      load_precomputed_mel: true
      hop_length: ${n_window_stride}
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: ${batch_size}
      num_workers: 16
      pin_memory: true

  optim:
    _target_: torch.optim.AdamW
    lr: 1e-5
    betas: [0.8, 0.99]

    sched:
      name: CosineAnnealing
      min_lr: 1e-7
      warmup_ratio: 0.2


trainer:
  num_nodes: 1
  devices: 1
  accelerator: gpu
  strategy: ddp_find_unused_parameters_true
  precision: bf16
  max_epochs: 10
  accumulate_grad_batches: 1
  enable_checkpointing: False  # Provided by exp_manager
  logger: false # Provided by exp_manager
  log_every_n_steps: 10
  check_val_every_n_epoch: 1
  benchmark: false

exp_manager:
  explicit_log_dir: ${log_dir}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: val_loss
    mode: min
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
    entity: null
  resume_if_exists: false
  resume_ignore_no_checkpoint: false
